name: Venti Deploy

on: push

jobs:
      ecr-deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: Terranovax/aws-ecr-deploy@v1
            with:
              access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              secret_access_key: ${{ secrets.AWS_SECRET_ID }}
              account_id: ${{ secrets.AWS_ACCOUNT_ID }}
              region: us-east-1
